<?php
/**
 * @file
 * Module to show a form when searches returns 0 (zero) hits
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function ding_zerohit_form_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_init().
 */
function ding_zerohit_form_init() {
  drupal_add_css(drupal_get_path('module', 'ding_zerohit_form') . '/css/ding_zerohit_form.css');
}

/**
 * Implements hook_menu().
 *
 * @return array
 */
function ding_zerohit_form_menu() {
  // Get the module path
  $path = drupal_get_path('module', 'ding_zerohit_form') . '/includes';

  $items = array();

  $items['admin/config/ting/zerohitform'] = array(
    'title' => 'Zero-hit form',
    'description' => 'Settings for the zero-hit form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_zerohit_form_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'ding_zerohit_form.admin.inc',
    'file path' => $path,
  );

  // Zero-hit form confirmation page
  $items['ting/zerohit'] = array(
    'title' => 'Zero-hit confirmation',
    'page callback' => '_zerohit_confirmation',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Prints the confirmation message after a successful submission.
 */
function _zerohit_confirmation() {
  $sid = isset($_GET['sid']) ? $_GET['sid'] : NULL;
  $values = variable_get('ding_zerohit_form', array());
  include_once(drupal_get_path('module', 'webform') . '/includes/webform.submissions.inc');

  if ($values['webform_id']) {
    // Data on the this submission of the zerohit form
    $submission = webform_get_submission($values['webform_id'], $sid, FALSE);

    // Confirmation message from current zerohit form
    $webform_node = node_load($values['webform_id']);
    //$confirmation_message = 'hello from current zerohit form';

    return theme('zerohit_confirmation', $webform_node, $submission);
  }
}

/**
 * Prepare for theming of the zerohit form submission confirmation.
 */
function template_preprocess_zerohit_confirmation(&$vars) {
  $confirmation = check_markup($vars['webform_node']->webform['confirmation'], $vars['node']->webform['confirmation_format'], FALSE);
  $vars['confirmation_message'] = $confirmation;
  $vars['user_description'] = check_plain($vars['submission']->data[2]['value'][0]);
  $vars['user_name'] = check_plain($vars['submission']->name);
}

/**
 * Implements hook_theme().
 */
function ding_zerohit_form_theme() {
  $items = array(
    'zerohit_confirmation' => array(
      'arguments' => array(
        'webform_node' => array(),
        'submission' => array(),
      ),
      'template' => 'zerohit-confirmation',
    ),
  );

  return $items;
}
